table Fact_Sales
	lineageTag: 75e51fcb-c7a6-4c2a-ab60-d9e5dfd3d536

	measure 'Total Sales Rows' = COUNTROWS(Fact_Sales)
		formatString: #,0
		lineageTag: ca71259e-3e0f-44ee-9cc5-aa5afcd230b7

	measure 'Successful Transactions' = CALCULATE([Total Sales Rows], Fact_Sales[TransactionOutcomeGroup] = "Success")
		formatString: #,0
		lineageTag: d0b9cf58-a3b9-4ee6-bba6-969a86ad6833

	measure 'Failed Attempts' = CALCULATE([Total Sales Rows], Fact_Sales[TransactionOutcomeGroup] = "Failed_or_Cancelled")
		formatString: #,0
		lineageTag: d0f474ac-9a3d-482b-8dde-525d962ab85a

	measure 'Refund Transactions' = CALCULATE([Total Sales Rows], Fact_Sales[TransactionOutcomeGroup] = "Refunded")
		formatString: #,0
		lineageTag: b972d533-27a3-4121-af6e-d91737b7aae6

	measure 'Overall Success Rate' = DIVIDE([Successful Transactions], [Total Sales Rows], 0)
		formatString: 0.00%
		lineageTag: 832c7218-d0f1-4de5-8c7f-4d057754c3c2

	measure 'Success Rate Pre 29/04' = CALCULATE([Overall Success Rate], Dim_Date[FullDate] < DATE(2020,4,29))
		formatString: 0.00%
		lineageTag: 12026d01-15b1-4b9c-96e1-8fea8051c072

	measure 'Success Rate Post 29/04' = CALCULATE([Overall Success Rate], Dim_Date[FullDate] >= DATE(2020,4,29))
		formatString: 0.00%
		lineageTag: 7113cfc2-1eae-4660-8dba-d42cb91bec17

	measure 'Successful Sales Value' = CALCULATE(SUM(Fact_Sales[TotalPrice]), Fact_Sales[TransactionOutcomeGroup] = "Success")
		formatString: #,0 ₫
		lineageTag: 8b1454d1-450d-4b8a-bff7-70dd50d3bc1a

	measure 'Value at Risk' = CALCULATE(SUM(Fact_Sales[TotalPrice]), Fact_Sales[TransactionOutcomeGroup] = "Failed_or_Cancelled")
		formatString: #,0 ₫
		lineageTag: c8f44dba-ff8f-41ac-beec-efaf13812276

	measure 'Total Refund Amount' = SUM(Fact_Sales[RefundedAmount])
		formatString: #,0 ₫
		lineageTag: 38732156-5f33-48a4-85e7-7374e9edf854

	measure 'Verified Refund Amount' = CALCULATE(SUM(Fact_Sales[RefundedAmount]), Fact_Sales[TransactionOutcomeGroup] = "Refunded")
		formatString: #,0 ₫
		lineageTag: bdbfd09e-94f2-4a6f-8b45-085c8231dc2d

	measure 'DQ Refund Exceptions' = COUNTROWS(Sales_DQ_Exceptions)
		formatString: #,0
		lineageTag: b9b2ba97-834d-4001-bbdf-5acdf583595d

	measure 'Active Machines Count' = CALCULATE(COUNTROWS(Dim_Machine), Dim_Machine[MachineStatus] = "ON")
		formatString: #,0
		lineageTag: 3631ced1-3236-4acf-86b6-5e3f2c1dca83

	measure 'Active Fleet Rate' = DIVIDE([Active Machines Count], [Total Machines Count], 0)
		formatString: 0.00%
		lineageTag: 9a844e6c-82eb-471d-9fc1-8bd5dc0ecb49

	measure 'Total Transfer Value' = SUM(Fact_MachineTransfer[TotalAmount])
		formatString: #,0 ₫
		lineageTag: d93edd7c-bad3-4355-a9ea-d9d554ea71d6

	measure 'Total Transfer Count' = COUNTROWS(Fact_MachineTransfer)
		formatString: #,0
		lineageTag: 5052a79b-8371-4648-9026-0fa89acc06da

	measure 'Refill to Sales Ratio' = DIVIDE([Total Transfer Value], [Successful Sales Value], 0)
		formatString: 0.00%
		lineageTag: c7eedc2f-c36a-4b41-86f5-2e7a086697c1

	measure 'Total PO Count' = COUNTROWS(Fact_PurchaseOrder)
		formatString: #,0
		lineageTag: 79993197-3ffd-4fa1-a532-6b8bfee28f21

	measure 'Total Inbound Value' = SUM(Fact_InboundInventory[TotalAmount])
		formatString: #,0 ₫
		lineageTag: 4a14053f-78e2-4c0e-b357-64a674d5e90e

	measure 'Average AOV' = DIVIDE([Successful Sales Value], [Successful Transactions], 0)
		formatString: #,0 ₫
		lineageTag: cf09bcf1-9999-45ed-9592-ebb518a44b1a

	measure 'Covid Lockdown Revenue' = CALCULATE([Successful Sales Value], Dim_Date[IsCovidLockdown] = TRUE())
		formatString: #,0 ₫
		lineageTag: 35799d05-1651-443c-8593-a2809b437c6a

	measure 'Top 20% Machine Revenue Share' =
			VAR MachineCount =
				COUNTROWS(ALLSELECTED(Dim_Machine[MachineCode]))
			VAR TopMachineCount =
				MAX(1, ROUNDUP(MachineCount * 0.2, 0))
			VAR TopRevenue =
				CALCULATE(
					[Successful Sales Value],
					TOPN(
						TopMachineCount,
						ALLSELECTED(Dim_Machine[MachineCode]),
						[Successful Sales Value], DESC,
						Dim_Machine[MachineCode], ASC
					)
				)
			VAR TotalRevenue =
				CALCULATE(
					[Successful Sales Value],
					ALLSELECTED(Dim_Machine[MachineCode])
				)
			RETURN
				DIVIDE(TopRevenue, TotalRevenue, 0)
		formatString: 0.00%
		lineageTag: 08dbae0f-6239-429d-a3dd-a0657b339471

	measure 'Data Quality Integrity Index' = [Refund Data Integrity Rate]
		formatString: 0.00%
		lineageTag: f705250f-0a1c-4689-ab0e-b5b95351eacb

	measure 'Report Title' = "SkillsHub Vietnam"
		lineageTag: 1c35ecde-0dc7-4ec5-9549-4c2d1816dfcd

	measure 'Failed Rate' = DIVIDE([Failed Attempts], [Total Sales Rows], 0)
		formatString: 0.00%
		lineageTag: 92860210-ebd2-4742-adf3-3a5c1101ae8d

	measure 'Refund Rate' = DIVIDE([Refund Transactions], [Total Sales Rows], 0)
		formatString: 0.00%
		lineageTag: 53f04750-f6e8-4ba7-b1e1-cd9312b21908

	measure 'Total Machines Count' = COUNTROWS(Dim_Machine)
		formatString: #,0
		lineageTag: 462f0169-4e32-4ea2-93e7-43a3ba076c60

	measure 'Revenue per Refill' = DIVIDE([Successful Sales Value], [Total Transfer Count], 0)
		formatString: #,0 ₫
		lineageTag: 795012ed-bb68-415f-ade5-39b86727725a

	measure 'Sales to Transfer Value Ratio' = DIVIDE([Successful Sales Value], [Total Transfer Value], 0)
		formatString: 0.00%
		lineageTag: 615734b7-8417-4499-8953-1970ff704bd6

	measure 'Average PO Lead Days' =
			AVERAGEX(
				FILTER(
					Fact_PurchaseOrder,
					NOT ISBLANK(Fact_PurchaseOrder[ReceivingDateKey]) &&
						NOT ISBLANK(Fact_PurchaseOrder[OrderDateKey])
				),
				VAR OrderKey =
					Fact_PurchaseOrder[OrderDateKey]
				VAR ReceiveKey =
					Fact_PurchaseOrder[ReceivingDateKey]
				VAR OrderDate =
					DATE(
						QUOTIENT(OrderKey, 10000),
						QUOTIENT(MOD(OrderKey, 10000), 100),
						MOD(OrderKey, 100)
					)
				VAR ReceiveDate =
					DATE(
						QUOTIENT(ReceiveKey, 10000),
						QUOTIENT(MOD(ReceiveKey, 10000), 100),
						MOD(ReceiveKey, 100)
					)
				RETURN
					DATEDIFF(OrderDate, ReceiveDate, DAY)
			)
		formatString: 0.0
		lineageTag: 137f0a24-69cc-4728-8f9b-1b0547ca42b8

	measure 'Revenue per Active Machine' = DIVIDE([Successful Sales Value], [Active Machines Count], 0)
		formatString: #,0 ₫
		lineageTag: 4a8b54da-41fc-43e3-819e-702a77e5cde8

	measure 'Refund Data Integrity Rate' = 1 - DIVIDE([DQ Refund Exceptions], [Total Sales Rows], 0)
		formatString: 0.00%
		lineageTag: dfa360f4-533c-4721-97fb-2204e3a17b3a

	measure 'Machine Revenue Rank' = RANKX(ALLSELECTED(Dim_Machine[MachineCode]), [Successful Sales Value],, DESC, Dense)
		formatString: #,0
		lineageTag: d3ce1c9b-6d2d-438c-b494-f275d71dd9fb

	measure 'Machine Action' =
			VAR RevenueValue =
				[Successful Sales Value]
			VAR AttemptCount =
				[Total Sales Rows]
			VAR SuccessRateValue =
				[Overall Success Rate]
			VAR RefillCount =
				[Total Transfer Count]
			VAR RefillEfficiency =
				[Revenue per Refill]
			VAR RevenueMedian =
				MEDIANX(
					ALLSELECTED(Dim_Machine[MachineCode]),
					CALCULATE([Successful Sales Value])
				)
			VAR AttemptsMedian =
				MEDIANX(
					ALLSELECTED(Dim_Machine[MachineCode]),
					CALCULATE([Total Sales Rows])
				)
			VAR SuccessBenchmark =
				CALCULATE(
					[Overall Success Rate],
					ALLSELECTED(Dim_Machine[MachineCode])
				)
			VAR EfficiencyMedian =
				MEDIANX(
					ALLSELECTED(Dim_Machine[MachineCode]),
					CALCULATE([Revenue per Refill])
				)
			RETURN
				SWITCH(
					TRUE(),
					RevenueValue >= RevenueMedian &&
						SuccessRateValue >= SuccessBenchmark, "KEEP / SCALE",
					AttemptCount >= AttemptsMedian &&
						SuccessRateValue < SuccessBenchmark, "FIX",
					AttemptCount < AttemptsMedian &&
						SuccessRateValue >= SuccessBenchmark, "RELOCATE",
					RevenueValue < RevenueMedian &&
						SuccessRateValue < SuccessBenchmark &&
						RefillCount > 0 &&
						RefillEfficiency < EfficiencyMedian, "REVIEW / REPLACE",
					"MONITOR"
				)
		lineageTag: dfc1ba63-f4ba-4d1c-8f67-c992dae02217

	measure 'Machine Action Reason' =
			VAR ActionLabel =
				[Machine Action]
			RETURN
				SWITCH(
					ActionLabel,
					"KEEP / SCALE", "Revenue and reliability are above the selected-fleet benchmark",
					"FIX", "Demand is material but transaction success is below benchmark",
					"RELOCATE", "Machine works reliably but demand is below the fleet median",
					"REVIEW / REPLACE", "Low revenue, low reliability and weak refill efficiency",
					"Insufficient evidence; continue monitoring"
				)
		lineageTag: 853ed0e7-231b-4af7-94f5-862ca8482cc4

	measure 'Machine Action Priority' = SWITCH([Machine Action], "FIX", 1, "REVIEW / REPLACE", 2, "RELOCATE", 3, "MONITOR", 4, "KEEP / SCALE", 5, 9)
		formatString: 0
		lineageTag: 869e04dc-20dd-4ff4-93d7-628b1089a3e8

	measure 'Machine Action Priority Label' = SWITCH([Machine Action], "FIX", "P1 - FIX", "REVIEW / REPLACE", "P2 - REVIEW / REPLACE", "RELOCATE", "P3 - RELOCATE", "MONITOR", "P4 - MONITOR", "KEEP / SCALE", "P5 - KEEP / SCALE", "P9 - UNCLASSIFIED")
		lineageTag: 8911760a-e0eb-42b3-8acc-f9c0fe50f061

	measure 'Keep Scale Machines' = SUMX(VALUES(Dim_Machine[MachineCode]), IF([Machine Action] = "KEEP / SCALE", 1, 0))
		formatString: #,0
		lineageTag: 9ee45b20-4211-4295-8b12-faa4eb77fe57

	measure 'Fix Machines' = SUMX(VALUES(Dim_Machine[MachineCode]), IF([Machine Action] = "FIX", 1, 0))
		formatString: #,0
		lineageTag: a811269d-9171-4ece-bced-107d2e817858

	measure 'Relocate Machines' = SUMX(VALUES(Dim_Machine[MachineCode]), IF([Machine Action] = "RELOCATE", 1, 0))
		formatString: #,0
		lineageTag: 3ca11c48-2c61-4bdd-81bd-86ef3514ffb1

	measure 'Review Replace Machines' = SUMX(VALUES(Dim_Machine[MachineCode]), IF([Machine Action] = "REVIEW / REPLACE", 1, 0))
		formatString: #,0
		lineageTag: 70b880b6-25ef-4e04-ae5d-306343e86234

	measure 'Monitor Machines' = SUMX(VALUES(Dim_Machine[MachineCode]), IF([Machine Action] = "MONITOR", 1, 0))
		formatString: #,0
		lineageTag: d0013059-9506-427d-9c96-fd6851f2e12c

	measure 'Machines with Transactions' = DISTINCTCOUNT(Fact_Sales[MachineCode])
		formatString: #,0
		lineageTag: 91420eaf-84f6-4d19-b1e8-3dde5d5dff31

	/// Operational watch line for failed transaction share.
	measure 'Failure Watch Threshold' = IF([Total Sales Rows] > 0, 0.15)
		formatString: 0.00%
		lineageTag: 9b71e5e7-3f5a-4d3d-9493-94898d8f3c8b

	column TransactionId
		dataType: int64
		formatString: 0
		lineageTag: 6e5f1896-4ff9-4d16-bd1b-55adfd04b051
		summarizeBy: count
		sourceColumn: TransactionId

	column DateKey
		dataType: int64
		formatString: 0
		lineageTag: 8f0d5c58-223d-4fc4-8b98-4413382af2a3
		summarizeBy: none
		sourceColumn: DateKey

	column Hour
		dataType: int64
		formatString: 0
		lineageTag: f58144ce-c0ae-4702-a121-9ece75035a8c
		summarizeBy: none
		sourceColumn: Hour

	column MachineCode
		dataType: string
		lineageTag: 391689b9-0a93-467b-9de3-b4d14a9e77e7
		summarizeBy: none
		sourceColumn: MachineCode

	column TotalPrice
		dataType: int64
		formatString: 0
		lineageTag: 9dad5a4f-8358-43cf-9559-f401ef439692
		summarizeBy: sum
		sourceColumn: TotalPrice

	column TransactionStatus
		dataType: string
		lineageTag: 5750f6ea-bbe9-448f-b7d5-9618384779c3
		summarizeBy: none
		sourceColumn: TransactionStatus

	column RefundedQuantity
		dataType: int64
		formatString: 0
		lineageTag: 999b1911-a92e-4dde-b8ca-630a8d852992
		summarizeBy: sum
		sourceColumn: RefundedQuantity

	column RefundedAmount
		dataType: int64
		formatString: 0
		lineageTag: 8cf928fe-ee35-4608-92db-00bc4c577151
		summarizeBy: sum
		sourceColumn: RefundedAmount

	column MachinePosition
		dataType: string
		lineageTag: a10d0083-1b0c-4c46-9c8b-625d23c799de
		summarizeBy: none
		sourceColumn: MachinePosition

	column ProductId
		dataType: int64
		formatString: 0
		lineageTag: eb84688a-3a05-4b55-9daa-7409dccc10f1
		summarizeBy: none
		sourceColumn: ProductId

	column TransactionOutcomeGroup
		dataType: string
		lineageTag: 0acd8dbe-94a6-4dc2-9bf4-ccf475cf6a1f
		summarizeBy: none
		sourceColumn: TransactionOutcomeGroup

	partition Fact_Sales = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\buimi\OneDrive\Documents\AI_AGENT\ANALYTIC\cleaned_dataset\Cleaned_StarSchema_VendingMachine.xlsx"), null, true),
				    Fact_Sales_Sheet = Source{[Item="Fact_Sales",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Fact_Sales_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"TransactionId", Int64.Type}, {"DateKey", Int64.Type}, {"Hour", Int64.Type}, {"MachineCode", type text}, {"ProductId", Int64.Type}, {"TotalPrice", Int64.Type}, {"TransactionStatus", type text}, {"RefundedQuantity", Int64.Type}, {"RefundedAmount", Int64.Type}, {"MachinePosition", type text}, {"TransactionOutcomeGroup", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

